cookies = ['Double Chocolate Cookie',
	   'Chocolate-Cookie mit Kürbiskernen und Habaneros',
	   'Schoko Cookie',
	   '￼Super Chunk Cookie',
	   'American Chocolate Chip Cookie',
	   'Chewy Chocolate Creamcheese Cookie',
	   'Schokolade-Minze-Keks',
	   'Erdnuss - Cookie',
	   'Schoko-Vanille-Cookie',
	   'Peanut Butter Cookie',
	   'Oreo Chocolate Chip Cookie',
	   'Zitronen-Cookie',
	   'Chocolate Chip Cookie',
	   'Bratapfel-Cookie',
	   'Frankenstein-Cookie',
	   'Welsh Cookie',
	   'Pecan-Cream-Cheese-Cookie',
	   'Cookie-Kuchen'
	   ]
