getraenke = ['einen Kaffe','eine Limonade','einen Kakao','einen Tee',
                     'einen Kräutertee aus elians Garten','eine Cola',
                     'kaltes Wasser','kalten Eistee','einen Raktajino',
                     'frischen Mate', 'eine Club Mate','ein Glas Gurkenwasser',
                     'einen Energydrink','einen Apfelsaft','einen Traubensaft',
                     'einen Muckefuck','einen Kiwismoothie', 'einen Spinatsmoothie',
                     'einen Orangensaft','einen Coconut Kiss','ein Glas Milch',
                     'einen Erdbeersmoothie','einen Kirschsaft',
                     'einen Latte Macciato','eine Tasse heiße Schokolade',
                     'ein Glas Sauerkrautwasser','einen Topf Kinderpunsch',
                     'einen Mango-Melonesmoothie','ein Glas Hoffnung',
                     'einen frischen Pfefferminztee','eine Eisschokolade',
                     'einen Eiskaffee','einen kalten Milchschake',
                     'eine kalte Afri Cola','ein lauwarmes Spezi',
                     'ein Glas Joylent', 'einen Monster Energy Drink',
                     'einen Fraktal Allmachtstrank', 'einen Heiltrank',
                     'einen großen Becher Blumenwasser', 'einen Erdbeershake',
                     'einen Blaubeersmoothie', 'eine Tasse Pfefferminztee',
                     'eine kalte Spezi', 'eine Tasse Hanftee',
                     'eine Karaffe Sprudelwasser', 'einen Kwas',
                     'einen kleinen Becher Kirsch-Bannane-Nektar',
                     'einen Rockstar Energy', 'eine Mio Mio Mate',
                     'eine Fritz!Cola', 'einen Ginger-Ale',
                     'ein Butterbier', 'ein Glass Laktosefreie Milch',
                     'einen Lebertran', 'eine Caprisonne',
                     'ein Moloko-Plus']

getraenke_after_work = ['einen pangalaktischen Donnergurgler', 'ein barel Madensirup', 'ein Becher Blutwein',
			'einen Schoppen Wein','einen doppelten Pfefferminzschnaps', 
			'sto gramm Vodka','ein Glas Whisky', 'a Mas Bier','einen Alexander','einen Americano',
			'einen Angel Face','einen Aviation','einen Bacardi cocktail','einen Between the Sheets',
			'einen Casino','einen Clover Club','einen Daiquiri','einen Derby','einen Dry Martini',
			'einen Gin Fizz','einen John Collins','einen Manhattan','einen Mary Pickford',
			'einen Monkey Gland','einen Negroni','einen Old Fashioned','einen Paradise',
			'einen Planters Punch','einen Porto flip','einen Ramos Fizz','einen Rusty Nail',
			'einen Sazerac','einen Screwdriver','einen Sidecar','einen Stinger','einen Tuxedo',
			'einen Whiskey Sour','einen White Lady','einen Bellini','einen Black Russian',
			'einen Bloody Mary','einen Caipirinha','einen Champagne cocktail','einen Cosmopolitan',
			'einen Cuba Libre','einen French Connection','einen French 75','einen Godfather',
			'einen Godmother','einen Golden Dream','einen Grasshopper','einen Harvey Wallbanger',
			'einen Hemingway Special','einen Horses Neck','einen Irish coffee','einen Kir',
			'einen Long Island Iced Tea','einen Mai Tai','einen Margarita','einen Mimosa',
			'einen Mint julep','einen Mojito','einen Moscow mule','einen Piña colada','einen Rose',
			'einen Sea Breeze','einen Sex on the Beach','einen Singapore Sling','einen Tequila Sunrise',
			'einen Barracuda','einen Bramble','einen B-52','einen Dark N Stormy','einen Dirty Martini',
			'einen Espresso Martini','einen French Martini','einen Kamikaze','einen Lemon Drop Martini',
			'einen Pisco Sour','einen Russian Spring Punch','einen Spritz Veneziano',
			'einen Tommys Margarita','einen Vampiro','einen Vesper','einen Yellow Bird']
